# This Github workflow automates the process of releasing weekly homework for MIDS-W203
name: Invite Members

# Schedule the action
on:
  # Add the following line to manually trigger actions
  workflow_dispatch: 
      
jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - name: Add members
        env: 
          MEMBERS: "smajhi@tulane.edu,abcd@example.com"
          PERM: "pull"

      
