# This Github workflow automates the process of releasing weekly homework solutions for MIDS-W203
name: Homework Solution

# Schedule the action
on:
  # The actions are scheduled by the following crontab. **All times are based in UTC**. The first two entries are minutes and hours (in UTC), and 
  # the last entry is the day (0: Sunday, 1: Monday,..., 6: Saturday). 
  # Example: 
  #   Suppose that I want to release the homeworks every Wednesday at 7:30pm PST, i.e., Thursday at 2:30am UTC.
  #   In the crontab, I would use '30 2 * * 4'. 
  #   For more, go to https://crontab.guru/#30_2_*_*_4    
  schedule:
    # Time in UTC
    - cron: '00 04 * * *'
      
jobs:
  solution:
    runs-on: ubuntu-latest
    steps:
      - name: Grant Access
        env: 
          W203_SECRET: ${{ secrets.W203 }}
        run: | 
          start_week=18
          current_week=$(date +%U)
          mids_week=$( printf '%02d' $((current_week - start_week + 1)) )
          repo="su_21_unit_${mids_week}_ls_sol"
          
          export DAY=$(($(date +%u) - 1))
          
          declare -A sections
          sections[1]=01
          sections[2]=02,03,04,05
          sections[3]=06,07
          sections[4]=08,10,12
          sections[6]=09,11
          sections[0]=01
          
          export IFS=','
          
          for section in ${sections[$DAY]}; do
            team="su_21_section_#{$section}"
            
            curl \
              -X PUT \
              -H "Accept: application/vnd.github.inertia-preview+json" \
              https://api.github.com/orgs/mids-w203/teams/${team}/repos/mids-w203/${repo} \
              -d '{"permission":"pull"}'
          done
